language: node_js
node_js: '6.4'
cache:
  apt: true
  directories:
  - node_modules
before_install:
- export TZ='Asia/Shanghai'
install:
- npm install hexo --save
- npm install hexo-cli -g
script:
- hexo clean
- hexo g
after_script:
- rm -rf .git
- git config --global user.name "Mryan2005"
- git config --global user.email "40586009+Mryan2005@users.noreply.github.com"
- cd public
- git init
- git remote add origin https://github.com/easygittool/easygittool.github.io.git
- git pull --rebase origin master
- git add .
- git commit -m "Travis CI Auto Builder"
- git push --force --quiet "https://${GH_Token}@${GH_WEB}" master:master
branches:
  only:
  - master
env:
  global:
  - GH_WEB: github.com/easygittool/easygittool.github.io.git
